### ISSUE TITLE
Speak Your Code - Assignment

### ISSUE THREAD

**Issue by TanAsMat** [TanAsMat/components-on-a-grid#1]
@thatkidmadri

https://user-images.githubusercontent.com/77473165/135001565-dd673ed9-fbb7-454e-8d91-5643dbccf7cd.mp4

d

**Comment by thatkidmadrid** [comment]
Just to be picky you can be more consistent when your'e saying `select <element>` 
so instead of "selector h1 ..." or "h1 selected ..." you can say "select h1"

when you spoke the `grid-template-areas` you confused column with row, so be careful with that. you can even say "first line ..., second line..." I know column/row can get confusing sometimes

I also notice you have multiple grids defined in the code (in your `body`, `.logo` and `main`) you should be able to get the layout with just one 2x2 grid on the `body`

markbot passed you so you get the grade, but please revisit this if you have the time
